import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import type { NextPage, GetServerSideProps, GetStaticProps } from 'next'

type fetchData = {
  userId: number
  id: number
  title: string
  body: string
}

type Props = {
  posts: fetchData[]
}

const Home: NextPage<Props> = ({ posts }) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
      <h1>Hello world</h1>

      {posts.map((item, key) => (
        <div key={key}>
          <h2>{item.title}</h2>
          <p>{item.body}</p>
          <p>userId: {item.userId}</p>
        </div>
      ))}
    </main>
  </>
)

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const posts = await res.json()

  return {
    props: {
      posts,
    },
  }
}

// export const getStaticProps: GetStaticProps<Props> = async () => {
//   return {
//     props: {
//       posts: [
//         {
//           userId: 1,
//           id: 1,
//           title: 'test',
//           body: 'test',
//         },
//         {
//           userId: 2,
//           id: 2,
//           title: 'test2',
//           body: 'test2',
//         },
//       ],
//     },
//   }
// }

export default Home
